import type {BlendMode, LayerRole} from "../editor/document";
import type {CommandShortcutID} from "../editor/shortcuts";
import type {ToolID} from "../editor/tools";

export const allBlendModes: BlendMode[] = ["normal", "darken", "multiply", "color-burn", "lighten", "screen", "color-dodge", "overlay", "soft-light", "hard-light", "difference", "exclusion", "hue", "saturation", "color", "luminosity", "addition", "subtract", "divide"];

export const blendModeText: Record<Language, Record<BlendMode, string>> = {
  en: {normal: "Normal", darken: "Darken", multiply: "Multiply", "color-burn": "Color burn", lighten: "Lighten", screen: "Screen", "color-dodge": "Color dodge", overlay: "Overlay", "soft-light": "Soft light", "hard-light": "Hard light", difference: "Difference", exclusion: "Exclusion", hue: "Hue", saturation: "Saturation", color: "Color", luminosity: "Luminosity", addition: "Addition", subtract: "Subtract", divide: "Divide"},
  zh: {normal: "正常", darken: "变暗", multiply: "正片叠底", "color-burn": "颜色加深", lighten: "变亮", screen: "滤色", "color-dodge": "颜色减淡", overlay: "叠加", "soft-light": "柔光", "hard-light": "强光", difference: "差值", exclusion: "排除", hue: "色相", saturation: "饱和度", color: "颜色", luminosity: "明度", addition: "相加", subtract: "减去", divide: "划分"},
};

export const layerRoleText: Record<Language, Record<LayerRole, string>> = {
  en: {standard: "Standard", background: "Background", reference: "Reference"},
  zh: {standard: "普通", background: "背景", reference: "参考"},
};

export type Language = "en" | "zh";

export const commandShortcutLabels: Record<Language, Record<CommandShortcutID, string>> = {
  en: {
    new: "New", newFromSelection: "New from selection", open: "Open", importPNG: "Import PNG", importSpriteSheet: "Import sprite sheet", importPNGSequence: "Import PNG sequence", save: "Save", saveAs: "Save as", exportPNG: "Export PNG", exportGIF: "Export animated GIF", exportSpriteSheet: "Export sprite sheet", exportPNGSequence: "Export PNG sequence", closeDocument: "Close document",
    undo: "Undo", redo: "Redo", selectAll: "Select all", deselect: "Deselect", reselect: "Reselect", copy: "Copy", copyMerged: "Copy merged", cut: "Cut", paste: "Paste", pasteSpecialNewSprite: "Paste as new sprite", pasteSpecialNewLayer: "Paste as new layer", pasteSpecialReferenceLayer: "Paste as reference layer", fillSelection: "Fill selection", strokeSelection: "Stroke selection", copySelectionToLayer: "Copy selection to new layer", cutSelectionToLayer: "Cut selection to new layer", copySelectedFramesToDocument: "Copy selected frames to another document", copySelectedLayersToDocument: "Copy selected layers to another document", shiftPixelsLeft: "Shift pixels left", shiftPixelsRight: "Shift pixels right", shiftPixelsUp: "Shift pixels up", shiftPixelsDown: "Shift pixels down",
    selectOpaque: "Select opaque pixels", selectColor: "Select foreground color", selectAllLayerCels: "Select all cels in layer", selectLinkedCels: "Select linked cels", invertSelection: "Invert selection", growSelection: "Grow selection", shrinkSelection: "Shrink selection", borderSelection: "Selection border", featherSelection: "Feather selection", scaleSelection: "Scale selection", rotateSelectionCCW: "Rotate selection counterclockwise", rotateSelectionCW: "Rotate selection clockwise", flipSelectionHorizontal: "Flip selection horizontally", flipSelectionVertical: "Flip selection vertically", applySelectionPosition: "Apply selection position", applySelectionRotation: "Rotate selection", createBrushFromSelection: "Create brush from selection", createPatternFromSelection: "Create pattern from selection", createSliceFromSelection: "Create slice from selection",
    duplicateSprite: "Duplicate sprite", spriteSize: "Sprite size", canvasSize: "Canvas size", trimCanvas: "Trim transparent borders", rotateSpriteCW: "Rotate sprite clockwise", rotateSpriteCCW: "Rotate sprite counterclockwise", rotateSprite180: "Rotate sprite 180 degrees", flipSpriteHorizontal: "Flip sprite horizontally", flipSpriteVertical: "Flip sprite vertically", colorConfiguration: "Color configuration", adjustmentBrightnessContrast: "Brightness / contrast", adjustmentHSL: "Hue / saturation", adjustmentInvert: "Invert", adjustmentConvolution: "Convolution", adjustmentMedian: "Median", adjustmentDespeckle: "Despeckle", adjustmentCurves: "Curves", adjustmentHSVHSL: "HSV / HSL", adjustmentChannels: "Channels", effectOutline: "Outline", effectShading: "Shading",
    addPaletteColor: "Add palette color", updatePaletteColor: "Edit palette color", removePaletteColor: "Remove palette color", extractPalette: "Extract palette", sortPalette: "Sort palette", saveDefaultPalette: "Save default palette", applyDefaultPalette: "Apply default palette", resetDefaultPalette: "Restore built-in palette", importPalette: "Import palette", exportGPL: "Export GPL palette", exportJASCPAL: "Export JASC-PAL palette",
    addLayer: "Add layer", addGroup: "Add layer group", addTilemapLayer: "Add tilemap layer", convertLayerToTilemap: "Convert layer to tilemap", duplicateLayer: "Duplicate layer", layerProperties: "Layer properties", moveLayerUp: "Move layer up", moveLayerDown: "Move layer down", mergeLayerDown: "Merge layer down", mergeSelectedLayers: "Merge selected layers", flattenVisibleLayers: "Flatten visible layers", toggleLayerVisibility: "Toggle layer visibility", toggleLayerLock: "Toggle layer lock", toggleAlphaLock: "Toggle alpha lock", toggleContinuous: "Toggle continuous cel",
    addFrame: "Add frame", newEmptyFrame: "New empty frame", duplicateFrame: "Duplicate frame", deleteFrame: "Delete frame", moveFrameBackward: "Move frame earlier", moveFrameForward: "Move frame later", previousFrame: "Previous frame", nextFrame: "Next frame", reverseFrames: "Reverse selected frames", createCels: "Create cels", duplicateCels: "Duplicate cels", duplicateLinkedCels: "Duplicate linked cels", deleteCels: "Delete cels", linkCels: "Link cels", unlinkCels: "Unlink cels", celProperties: "Cel properties", applyCelTransform: "Apply cel transform", rasterizeCels: "Rasterize cels", togglePlayback: "Play / pause animation", addTag: "Add frame tag", editTag: "Edit frame tag", deleteTag: "Delete frame tag", focusTag: "Focus active tag",
    toggleInspector: "Toggle inspector", toggleTimeline: "Toggle timeline", togglePixelGrid: "Toggle pixel grid", toggleOnionSkin: "Toggle onion skin", toggleCanvasOnly: "Canvas-only mode", showAllPanels: "Show all panels", toggleFullscreen: "Toggle full screen", detachedPreview: "Detached animation preview", resetWorkspace: "Reset workspace layout", showHistory: "Show history", openPreferences: "Open preferences", toggleTheme: "Toggle theme", switchLanguage: "Switch language",
    toggleGridSnap: "Toggle grid snapping", toggleMirrorX: "Toggle horizontal mirror", toggleMirrorY: "Toggle vertical mirror", toggleTileX: "Toggle horizontal tiling", toggleTileY: "Toggle vertical tiling", addVerticalGuide: "Add vertical guide", addHorizontalGuide: "Add horizontal guide", setRGBA: "Use RGBA mode", setGrayscale: "Use grayscale mode", setIndexed: "Use indexed mode", setBitmap: "Use bitmap mode", zoomIn: "Zoom in", zoomOut: "Zoom out", delete: "Delete",
  },
  zh: {
    new: "新建", newFromSelection: "从选区新建", open: "打开", importPNG: "导入 PNG", importSpriteSheet: "导入精灵图", importPNGSequence: "导入 PNG 序列", save: "保存", saveAs: "另存为", exportPNG: "导出 PNG", exportGIF: "导出 GIF 动画", exportSpriteSheet: "导出精灵图", exportPNGSequence: "导出 PNG 序列", closeDocument: "关闭文件",
    undo: "撤销", redo: "重做", selectAll: "全选", deselect: "取消选择", reselect: "重新选择", copy: "复制", copyMerged: "复制合并结果", cut: "剪切", paste: "粘贴", pasteSpecialNewSprite: "粘贴为新项目", pasteSpecialNewLayer: "粘贴为新图层", pasteSpecialReferenceLayer: "粘贴为参考图层", fillSelection: "填充选区", strokeSelection: "描边选区", copySelectionToLayer: "复制选区到新图层", cutSelectionToLayer: "剪切选区到新图层", copySelectedFramesToDocument: "复制所选帧到其他文件", copySelectedLayersToDocument: "复制所选图层到其他文件", shiftPixelsLeft: "向左环绕平移像素", shiftPixelsRight: "向右环绕平移像素", shiftPixelsUp: "向上环绕平移像素", shiftPixelsDown: "向下环绕平移像素",
    selectOpaque: "选择不透明像素", selectColor: "选择前景色", selectAllLayerCels: "选择当前图层全部动画格", selectLinkedCels: "选择链接动画格", invertSelection: "反选", growSelection: "扩展选区", shrinkSelection: "收缩选区", borderSelection: "选区边框", featherSelection: "羽化选区", scaleSelection: "缩放选区", rotateSelectionCCW: "逆时针旋转选区", rotateSelectionCW: "顺时针旋转选区", flipSelectionHorizontal: "水平翻转选区", flipSelectionVertical: "垂直翻转选区", applySelectionPosition: "应用选区位置", applySelectionRotation: "旋转选区", createBrushFromSelection: "从选区创建笔刷", createPatternFromSelection: "从选区创建图案", createSliceFromSelection: "从选区创建切片",
    duplicateSprite: "复制精灵", spriteSize: "缩放图像内容", canvasSize: "画布尺寸", trimCanvas: "裁去透明边缘", rotateSpriteCW: "顺时针旋转图像", rotateSpriteCCW: "逆时针旋转图像", rotateSprite180: "旋转图像 180 度", flipSpriteHorizontal: "水平翻转图像", flipSpriteVertical: "垂直翻转图像", colorConfiguration: "颜色配置", adjustmentBrightnessContrast: "亮度 / 对比度", adjustmentHSL: "色相 / 饱和度", adjustmentInvert: "反相", adjustmentConvolution: "卷积", adjustmentMedian: "中值滤波", adjustmentDespeckle: "去斑", adjustmentCurves: "曲线", adjustmentHSVHSL: "HSV / HSL", adjustmentChannels: "通道", effectOutline: "轮廓", effectShading: "着色",
    addPaletteColor: "添加调色板颜色", updatePaletteColor: "编辑调色板颜色", removePaletteColor: "移除调色板颜色", extractPalette: "提取调色板", sortPalette: "整理调色板", saveDefaultPalette: "保存默认调色板", applyDefaultPalette: "应用默认调色板", resetDefaultPalette: "恢复内置调色板", importPalette: "导入调色板", exportGPL: "导出 GPL 调色板", exportJASCPAL: "导出 JASC-PAL 调色板",
    addLayer: "新建图层", addGroup: "新建图层组", addTilemapLayer: "新建图块地图图层", convertLayerToTilemap: "将图层转换为图块地图", duplicateLayer: "复制图层", layerProperties: "图层属性", moveLayerUp: "上移图层", moveLayerDown: "下移图层", mergeLayerDown: "向下合并图层", mergeSelectedLayers: "合并所选图层", flattenVisibleLayers: "拼合可见图层", toggleLayerVisibility: "切换图层可见性", toggleLayerLock: "切换图层锁定", toggleAlphaLock: "切换锁定透明度", toggleContinuous: "切换连续动画格",
    addFrame: "新建帧", newEmptyFrame: "新建空帧", duplicateFrame: "复制帧", deleteFrame: "删除帧", moveFrameBackward: "前移帧", moveFrameForward: "后移帧", previousFrame: "上一帧", nextFrame: "下一帧", reverseFrames: "反转所选帧", createCels: "创建动画格", duplicateCels: "复制动画格", duplicateLinkedCels: "复制并链接动画格", deleteCels: "删除动画格", linkCels: "链接动画格", unlinkCels: "取消链接动画格", celProperties: "动画格属性", applyCelTransform: "应用动画格变换", rasterizeCels: "栅格化动画格", togglePlayback: "播放 / 暂停动画", addTag: "添加帧标签", editTag: "编辑帧标签", deleteTag: "删除帧标签", focusTag: "聚焦当前帧标签",
    toggleInspector: "显示 / 隐藏侧栏", toggleTimeline: "显示 / 隐藏时间轴", togglePixelGrid: "切换像素网格", toggleOnionSkin: "切换洋葱皮", toggleCanvasOnly: "画布独占模式", showAllPanels: "显示所有面板", toggleFullscreen: "切换全屏", detachedPreview: "独立动画预览", resetWorkspace: "重置工作区布局", showHistory: "显示历史记录", openPreferences: "打开偏好设置", toggleTheme: "切换主题", switchLanguage: "切换语言",
    toggleGridSnap: "切换网格吸附", toggleMirrorX: "切换水平对称", toggleMirrorY: "切换垂直对称", toggleTileX: "切换水平平铺", toggleTileY: "切换垂直平铺", addVerticalGuide: "添加垂直辅助线", addHorizontalGuide: "添加水平辅助线", setRGBA: "使用 RGBA 模式", setGrayscale: "使用灰度模式", setIndexed: "使用索引色模式", setBitmap: "使用位图模式", zoomIn: "放大", zoomOut: "缩小", delete: "删除",
  },
};

export const labels: Record<Language, {
  file: string; newProject: string; openProject: string; importPNG: string; saveProject: string; saveAs: string;
  exportPNG: string; exportGIF: string; exportSpriteSheet: string; recentProjects: string;
  openDocuments: string; closeDocument: string; previousDocuments: string; nextDocuments: string;
  undo: string; redo: string; toggleTheme: string; switchLanguage: string; tools: string;
  color: string; currentColor: string; palette: string; useColor: string; selection: string; mode: string;
  foreground: string; background: string; swapColors: string; alpha: string; brush: string; brushSize: string;
  brushShape: string; squareBrush: string; circleBrush: string; addColor: string; removeColor: string; editColor: string;
  brushPreset: string; crossBrush: string; diamondBrush: string; customBrush: string; brushFromSelection: string; brushSpacing: string; pixelPerfect: string; pressure: string; polygonSides: string;
  colorMode: string; rgbaMode: string; grayscaleMode: string; indexedMode: string; bitmapMode: string; extractPalette: string; sortPalette: string;
  selectionReplace: string; selectionAdd: string; selectionSubtract: string; selectionIntersect: string;
  selectionShape: string; rectangularSelection: string; ellipticalSelection: string; lassoSelection: string; polygonSelection: string; magicWand: string; tolerance: string; selectOpaque: string; selectColor: string; invertSelection: string; reselect: string; growSelection: string; shrinkSelection: string; borderSelection: string; amount: string;
  transform: string; transformModeLabel: string; transformScale: string; transformPerspective: string; transformDistort: string; scaleSelection: string; rotateClockwise: string; rotateCounterclockwise: string; flipHorizontal: string; flipVertical: string;
  arbitraryRotation: string; applyRotation: string;
  layers: string; addLayer: string; addGroup: string; duplicateLayer: string;
  moveLayerUp: string; moveLayerDown: string; mergeLayerDown: string; hideLayer: string; showLayer: string;
  renameLayer: string; lockLayer: string; unlockLayer: string; collapseGroup: string; expandGroup: string;
  opacity: string; layerOpacity: string; blendMode: string; normal: string; multiply: string; screen: string; overlay: string;
  animation: string; addFrame: string; newEmptyFrame: string; duplicateFrame: string; deleteFrame: string; moveFrameBackward: string;
  moveFrameForward: string; previousFrame: string; nextFrame: string; frames: string; pause: string; play: string; onionSkin: string; loop: string;
  linkCels: string; unlinkCels: string; duplicateCels: string; duplicateLinkedCels: string; tags: string; noTag: string; addTag: string; editTag: string; deleteTag: string; focusTag: string;
  celTransform: string; angle: string; offsetX: string; offsetY: string; applyCelTransform: string; rasterizeCels: string;
  tagName: string; direction: string; forward: string; reverse: string; pingpong: string; loopStart: string; loopEnd: string;
  exportOptions: string; export: string; scale: string; applyPixelRatio: string; playback: string; once: string; forever: string; repeatCount: string;
  frameRange: string; allFrames: string; selectedFrames: string; loopRange: string; layout: string;
  sheetHorizontal: string; sheetVertical: string; sheetGrid: string; columns: string; borderPadding: string; framePadding: string; atlasJSON: string;
  to: string; zoomOut: string; zoomIn: string; newDocument: string; resizeCanvas: string; width: string; height: string;
  horizontal: string; vertical: string; left: string; center: string; right: string; top: string; bottom: string;
  cancel: string; create: string; apply: string; sizeError: string; projectName: string; frame: string;
  visibleLayerThumbnail: string; hiddenLayerThumbnail: string; restoreRecovery: string;
  defaultDocumentName: string; layerBaseName: string; groupBaseName: string; tagBaseName: string; copySuffix: string;
  closeUnsaved: (name: string) => string; toolsByID: Record<ToolID, string>;
}> = {
  en: {
    file: "File", newProject: "New project", openProject: "Open project", importPNG: "Import PNG", saveProject: "Save", saveAs: "Save as",
    exportPNG: "Export PNG", exportGIF: "Export animated GIF", exportSpriteSheet: "Export sprite sheet", recentProjects: "Recent projects", openDocuments: "Open documents", closeDocument: "Close", previousDocuments: "Previous documents", nextDocuments: "Next documents",
    undo: "Undo", redo: "Redo", toggleTheme: "Toggle theme", switchLanguage: "Switch to Chinese", tools: "Tools",
    color: "Color", currentColor: "Current color", palette: "Palette", useColor: "Use color", selection: "Selection", mode: "Mode",
    foreground: "Foreground", background: "Background", swapColors: "Swap foreground and background", alpha: "Alpha", brush: "Brush", brushSize: "Brush size",
    brushShape: "Brush shape", squareBrush: "Square", circleBrush: "Circle", addColor: "Add current color", removeColor: "Remove selected color", editColor: "Replace selected color with current color",
    brushPreset: "Brush preset", crossBrush: "Cross", diamondBrush: "Diamond", customBrush: "Custom", brushFromSelection: "Create brush from selection", brushSpacing: "Spacing", pixelPerfect: "Pixel perfect", pressure: "Pen pressure", polygonSides: "Sides",
    colorMode: "Color mode", rgbaMode: "RGBA", grayscaleMode: "Grayscale", indexedMode: "Indexed", bitmapMode: "Bitmap (1-bit)", extractPalette: "Extract palette from artwork", sortPalette: "Sort palette by hue",
    selectionReplace: "Replace", selectionAdd: "Add", selectionSubtract: "Subtract", selectionIntersect: "Intersect",
    selectionShape: "Shape", rectangularSelection: "Rectangle", ellipticalSelection: "Ellipse", lassoSelection: "Lasso", polygonSelection: "Polygon", magicWand: "Magic wand", tolerance: "Tolerance", selectOpaque: "Select opaque pixels", selectColor: "Select foreground color", invertSelection: "Invert selection", reselect: "Reselect", growSelection: "Grow selection", shrinkSelection: "Shrink selection", borderSelection: "Selection border", amount: "Amount",
    transform: "Transform", transformModeLabel: "Mode", transformScale: "Scale", transformPerspective: "Perspective", transformDistort: "Distort", scaleSelection: "Scale selection", rotateClockwise: "Rotate clockwise", rotateCounterclockwise: "Rotate counterclockwise", flipHorizontal: "Flip horizontally", flipVertical: "Flip vertically",
    arbitraryRotation: "Rotation angle", applyRotation: "Rotate selection",
    layers: "Layers", addLayer: "Add layer", addGroup: "Add layer group", duplicateLayer: "Duplicate layer",
    moveLayerUp: "Move layer up", moveLayerDown: "Move layer down", mergeLayerDown: "Merge layer down", hideLayer: "Hide layer", showLayer: "Show layer",
    renameLayer: "Rename layer", lockLayer: "Lock layer", unlockLayer: "Unlock layer", collapseGroup: "Collapse group", expandGroup: "Expand group",
    opacity: "Opacity", layerOpacity: "Layer opacity", blendMode: "Blend mode", normal: "Normal", multiply: "Multiply", screen: "Screen", overlay: "Overlay",
    animation: "Animation", addFrame: "Add frame", newEmptyFrame: "New empty frame", duplicateFrame: "Duplicate frame", deleteFrame: "Delete frame", moveFrameBackward: "Move frame earlier",
    moveFrameForward: "Move frame later", previousFrame: "Previous frame", nextFrame: "Next frame", frames: "Frames", pause: "Pause", play: "Play", onionSkin: "Onion skin", loop: "Loop",
    linkCels: "Link selected cels", unlinkCels: "Unlink selected cels", duplicateCels: "Duplicate selected cels", duplicateLinkedCels: "Duplicate selected cels as linked", tags: "Frame tags", noTag: "No active tag", addTag: "Add frame tag", editTag: "Edit frame tag", deleteTag: "Delete frame tag", focusTag: "Focus active tag",
    celTransform: "Selected cel transform", angle: "Angle", offsetX: "Offset X", offsetY: "Offset Y", applyCelTransform: "Apply to selected cels", rasterizeCels: "Rasterize to canvas",
    tagName: "Tag name", direction: "Direction", forward: "Forward", reverse: "Reverse", pingpong: "Ping-pong", loopStart: "Loop start", loopEnd: "Loop end",
    exportOptions: "Export options", export: "Export", scale: "Scale", applyPixelRatio: "Apply pixel ratio", playback: "Playback", once: "Once", forever: "Forever", repeatCount: "Repeat count",
    frameRange: "Frame range", allFrames: "All frames", selectedFrames: "Selected frames", loopRange: "Loop range", layout: "Layout",
    sheetHorizontal: "Horizontal", sheetVertical: "Vertical", sheetGrid: "Grid", columns: "Columns", borderPadding: "Border padding", framePadding: "Frame padding", atlasJSON: "Write atlas JSON",
    to: "to", zoomOut: "Zoom out", zoomIn: "Zoom in",
    newDocument: "New document", resizeCanvas: "Resize canvas", width: "Width", height: "Height",
    horizontal: "Horizontal anchor", vertical: "Vertical anchor", left: "Left", center: "Center", right: "Right", top: "Top", bottom: "Bottom",
    cancel: "Cancel", create: "Create", apply: "Apply", sizeError: "Enter whole-number dimensions from 1 to 2048.",
    projectName: "Project name", frame: "Frame", visibleLayerThumbnail: "Visible layer thumbnail", hiddenLayerThumbnail: "Hidden layer thumbnail",
    restoreRecovery: "Restore the local recovery project?", defaultDocumentName: "untitled.pixio", layerBaseName: "Layer", groupBaseName: "Group", tagBaseName: "Tag", copySuffix: "copy",
    closeUnsaved: (name) => `Close ${name} without saving changes?`,
    toolsByID: {pencil: "Pencil", eraser: "Eraser", eyedropper: "Eyedropper", zoom: "Zoom", hand: "Hand", move: "Move", line: "Line", rectangle: "Rectangle", ellipse: "Ellipse", curve: "Curve", polyline: "Polyline", polygon: "Polygon", fill: "Fill", gradient: "Gradient", spray: "Spray", blur: "Blur", jumble: "Jumble", contour: "Contour", "replace-color": "Replace color", selection: "Selection", transform: "Transform", crop: "Crop", slice: "Slice", text: "Text"},
  },
  zh: {
    file: "文件", newProject: "新建项目", openProject: "打开项目", importPNG: "导入 PNG", saveProject: "保存", saveAs: "另存为",
    exportPNG: "导出 PNG", exportGIF: "导出 GIF 动画", exportSpriteSheet: "导出精灵图", recentProjects: "最近项目", openDocuments: "已打开的文件", closeDocument: "关闭", previousDocuments: "向前滚动文件", nextDocuments: "向后滚动文件",
    undo: "撤销", redo: "重做", toggleTheme: "切换主题", switchLanguage: "切换为 English", tools: "工具",
    color: "颜色", currentColor: "当前颜色", palette: "调色板", useColor: "使用颜色", selection: "选区", mode: "组合",
    foreground: "前景色", background: "背景色", swapColors: "交换前景色和背景色", alpha: "透明度", brush: "笔刷", brushSize: "笔刷尺寸",
    brushShape: "笔刷形状", squareBrush: "方形", circleBrush: "圆形", addColor: "添加当前颜色", removeColor: "移除所选颜色", editColor: "用当前颜色替换所选颜色",
    brushPreset: "笔刷预设", crossBrush: "十字", diamondBrush: "菱形", customBrush: "自定义", brushFromSelection: "从选区创建笔刷", brushSpacing: "间距", pixelPerfect: "像素完美", pressure: "压感", polygonSides: "边数",
    colorMode: "颜色模式", rgbaMode: "RGBA", grayscaleMode: "灰度", indexedMode: "索引色", bitmapMode: "位图（1 位）", extractPalette: "从作品提取调色板", sortPalette: "按色相整理调色板",
    selectionReplace: "替换", selectionAdd: "添加", selectionSubtract: "减去", selectionIntersect: "相交",
    selectionShape: "形状", rectangularSelection: "矩形", ellipticalSelection: "椭圆", lassoSelection: "套索", polygonSelection: "多边形", magicWand: "魔棒", tolerance: "容差", selectOpaque: "选择不透明像素", selectColor: "选择前景色", invertSelection: "反选", reselect: "重新选择", growSelection: "扩展选区", shrinkSelection: "收缩选区", borderSelection: "选区边框", amount: "数量",
    transform: "变换", transformModeLabel: "模式", transformScale: "缩放", transformPerspective: "透视", transformDistort: "扭曲", scaleSelection: "缩放选区", rotateClockwise: "顺时针旋转", rotateCounterclockwise: "逆时针旋转", flipHorizontal: "水平翻转", flipVertical: "垂直翻转",
    arbitraryRotation: "旋转角度", applyRotation: "旋转选区",
    layers: "图层", addLayer: "新建图层", addGroup: "新建图层组", duplicateLayer: "复制图层",
    moveLayerUp: "上移图层", moveLayerDown: "下移图层", mergeLayerDown: "向下合并图层", hideLayer: "隐藏图层", showLayer: "显示图层",
    renameLayer: "重命名图层", lockLayer: "锁定图层", unlockLayer: "解锁图层", collapseGroup: "折叠图层组", expandGroup: "展开图层组",
    opacity: "不透明度", layerOpacity: "图层不透明度", blendMode: "混合模式", normal: "正常", multiply: "正片叠底", screen: "滤色", overlay: "叠加",
    animation: "动画", addFrame: "新建帧", newEmptyFrame: "新建空帧", duplicateFrame: "复制帧", deleteFrame: "删除帧", moveFrameBackward: "前移帧",
    moveFrameForward: "后移帧", previousFrame: "上一帧", nextFrame: "下一帧", frames: "帧", pause: "暂停", play: "播放", onionSkin: "洋葱皮", loop: "循环",
    linkCels: "链接所选动画格", unlinkCels: "取消链接所选动画格", duplicateCels: "复制所选动画格", duplicateLinkedCels: "复制并链接所选动画格", tags: "帧标签", noTag: "未选择帧标签", addTag: "添加帧标签", editTag: "编辑帧标签", deleteTag: "删除帧标签", focusTag: "聚焦当前帧标签",
    celTransform: "所选动画格变换", angle: "角度", offsetX: "水平偏移", offsetY: "垂直偏移", applyCelTransform: "应用到所选动画格", rasterizeCels: "栅格化到画布",
    tagName: "标签名称", direction: "方向", forward: "正向", reverse: "反向", pingpong: "往返", loopStart: "循环起点", loopEnd: "循环终点",
    exportOptions: "导出选项", export: "导出", scale: "缩放", applyPixelRatio: "应用像素宽高比", playback: "播放方式", once: "一次", forever: "无限循环", repeatCount: "循环次数",
    frameRange: "帧范围", allFrames: "全部帧", selectedFrames: "所选帧", loopRange: "循环范围", layout: "布局",
    sheetHorizontal: "横向", sheetVertical: "纵向", sheetGrid: "网格", columns: "列数", borderPadding: "外边距", framePadding: "帧间距", atlasJSON: "生成图集 JSON",
    to: "至", zoomOut: "缩小", zoomIn: "放大",
    newDocument: "新建文件", resizeCanvas: "调整画布尺寸", width: "宽度", height: "高度",
    horizontal: "水平锚点", vertical: "垂直锚点", left: "左侧", center: "居中", right: "右侧", top: "顶部", bottom: "底部",
    cancel: "取消", create: "创建", apply: "应用", sizeError: "请输入 1 到 2048 的整数尺寸。",
    projectName: "项目名称", frame: "帧", visibleLayerThumbnail: "可见图层缩略图", hiddenLayerThumbnail: "隐藏图层缩略图",
    restoreRecovery: "是否恢复本地自动保存的项目？", defaultDocumentName: "未命名.pixio", layerBaseName: "图层", groupBaseName: "组", tagBaseName: "标签", copySuffix: "副本",
    closeUnsaved: (name) => `关闭 ${name} 并放弃未保存的更改？`,
    toolsByID: {pencil: "铅笔", eraser: "橡皮擦", eyedropper: "吸管", zoom: "缩放", hand: "抓手", move: "移动", line: "直线", rectangle: "矩形", ellipse: "椭圆", curve: "曲线", polyline: "折线", polygon: "多边形", fill: "填充", gradient: "渐变", spray: "喷枪", blur: "模糊", jumble: "抖动", contour: "轮廓", "replace-color": "颜色替换", selection: "选区", transform: "变换", crop: "裁剪", slice: "切片", text: "文字"},
  },
};

export function localizeStatus(value: string, language: Language): string {
  if (language === "en") return value;
  const named = chineseStatus[value];
  if (named) return named;
  const tool = (Object.keys(labels.en.toolsByID) as ToolID[]).find((id) => labels.en.toolsByID[id] === value);
  if (tool) return labels.zh.toolsByID[tool];
  const projectEntryTooLarge = value.match(/^project entry (.+) is too large$/);
  if (projectEntryTooLarge) return `项目条目 ${projectEntryTooLarge[1]} 过大`;
  const celDimensions = value.match(/^cel (.+) dimensions do not match manifest$/);
  if (celDimensions) return `动画格 ${celDimensions[1]} 的尺寸与项目清单不一致`;
  const gifDuration = value.match(/^GIF duration exceeds (\d+) centiseconds$/);
  if (gifDuration) return `GIF 帧时长超过 ${gifDuration[1]} 个百分之一秒`;
  const sizeLimit = value.match(/^(thumbnail|manifest) exceeds (\d+) bytes$/);
  if (sizeLimit) return `${sizeLimit[1] === "thumbnail" ? "缩略图" : "项目清单"}超过 ${sizeLimit[2]} 字节限制`;
  const pngSequenceExport = value.match(/^Exported (\d+) PNG frames$/);
  if (pngSequenceExport) return `已导出 ${pngSequenceExport[1]} 个 PNG 帧`;
  const splitSpriteSheetExport = value.match(/^Exported (tag|layer) sprite sheets$/);
  if (splitSpriteSheetExport) return `已导出按${splitSpriteSheetExport[1] === "tag" ? "帧标签" : "图层"}拆分的精灵图`;
  const prefixed = [
    ["Opened ", "已打开 "],
    ["Recovered ", "已恢复 "],
    ["Imported ", "已导入 "],
    ["Saved ", "已保存 "],
    ["Exported ", "已导出 "],
    ["Undid ", "已撤销："],
    ["Redid ", "已重做："],
    ["open PNG: ", "打开 PNG 失败："],
    ["rewind PNG: ", "重置 PNG 读取位置失败："],
    ["decode PNG: ", "解析 PNG 失败："],
    ["decode project: ", "解析项目失败："],
    ["decode recovery: ", "解析恢复文件失败："],
    ["encode recovery: ", "编码恢复文件失败："],
    ["sync recovery: ", "同步恢复文件失败："],
    ["read recovery: ", "读取恢复文件失败："],
    ["clear recovery: ", "清除恢复文件失败："],
    ["find recovery directory: ", "查找恢复目录失败："],
    ["create recovery directory: ", "创建恢复目录失败："],
    ["create temporary recovery: ", "创建临时恢复文件失败："],
    ["write recovery: ", "写入恢复文件失败："],
    ["close recovery: ", "关闭恢复文件失败："],
    ["replace recovery: ", "替换恢复文件失败："],
    ["encode opened project: ", "编码已打开项目失败："],
    ["encode project: ", "编码项目失败："],
    ["open project: ", "打开项目失败："],
    ["invalid project entry ", "无效的项目条目 "],
    ["duplicate project entry ", "重复的项目条目 "],
    ["project is missing cel image ", "项目缺少动画格图片 "],
    ["decode manifest: ", "解析项目清单失败："],
    ["create temporary project: ", "创建临时项目失败："],
    ["close temporary project: ", "关闭临时项目失败："],
    ["sync temporary project: ", "同步临时项目失败："],
    ["replace project: ", "替换项目失败："],
    ["encode empty thumbnail: ", "编码空缩略图失败："],
    ["create cel entry: ", "创建动画格条目失败："],
    ["encode cel ", "编码动画格失败："],
    ["write cel ", "写入动画格失败："],
    ["encode manifest: ", "编码项目清单失败："],
    ["manifest exceeds ", "项目清单超过限制："],
    ["create manifest: ", "创建项目清单失败："],
    ["write manifest: ", "写入项目清单失败："],
    ["create thumbnail: ", "创建缩略图失败："],
    ["encode thumbnail: ", "编码缩略图失败："],
    ["thumbnail exceeds ", "缩略图超过限制："],
    ["write thumbnail: ", "写入缩略图失败："],
    ["close project archive: ", "关闭项目文件失败："],
    ["open project entry: ", "打开项目条目失败："],
    ["read project entry ", "读取项目条目失败："],
    ["decode cel ", "解析动画格失败："],
    ["create PNG: ", "创建 PNG 失败："],
    ["encode PNG: ", "编码 PNG 失败："],
    ["sync PNG: ", "同步 PNG 失败："],
    ["close PNG: ", "关闭 PNG 失败："],
    ["rename PNG: ", "替换 PNG 失败："],
    ["create GIF: ", "创建 GIF 失败："],
    ["encode GIF: ", "编码 GIF 失败："],
    ["sync GIF: ", "同步 GIF 失败："],
    ["close GIF: ", "关闭 GIF 失败："],
    ["rename GIF: ", "替换 GIF 失败："],
    ["create sprite sheet: ", "创建精灵图失败："],
    ["encode sprite sheet: ", "编码精灵图失败："],
    ["sync sprite sheet: ", "同步精灵图失败："],
    ["close sprite sheet: ", "关闭精灵图失败："],
    ["rename sprite sheet: ", "替换精灵图失败："],
    ["GIF duration exceeds ", "GIF 帧时长超过限制："],
    ["image dimensions exceed ", "图片尺寸超过限制："],
    ["invalid RGBA buffer: ", "RGBA 像素数据无效："],
    ["unsupported .pixio format version ", "不支持的 .pixio 格式版本 "],
    ["project is missing ", "项目缺少 "],
    ["project entry ", "项目条目 "],
  ] as const;
  for (const [source, target] of prefixed) if (value.startsWith(source)) return `${target}${localizeStatus(value.slice(source.length), language)}`;
  if (value.endsWith(" is locked")) return `${value.slice(0, -10)} 已锁定`;
  return value;
}

const chineseStatus: Record<string, string> = {
  Ready: "就绪",
  "New project": "新建项目",
  "Saving project...": "正在保存项目...",
  "Save cancelled": "已取消保存",
  "Opening project...": "正在打开项目...",
  "Open cancelled": "已取消打开",
  "Exporting...": "正在导出...",
  "Export cancelled": "已取消导出",
  "Exporting GIF...": "正在导出 GIF...",
  "Exporting sprite sheet...": "正在导出精灵图...",
  "PNG export is available in the desktop app": "PNG 导出仅在桌面应用中可用",
  "Animation export is available in the desktop app": "动画导出仅在桌面应用中可用",
  "Project saving is available in the desktop app": "项目保存仅在桌面应用中可用",
  "Project opening is available in the desktop app": "项目打开仅在桌面应用中可用",
  "PNG import is available in the desktop app": "PNG 导入仅在桌面应用中可用",
  "Recent projects open in the desktop app": "最近项目仅能在桌面应用中打开",
  "Export failed": "导出失败",
  "Save failed": "保存失败",
  "Open failed": "打开失败",
  "Import failed": "导入失败",
  "application is not ready": "应用尚未就绪",
  "invalid PNG dimensions": "PNG 尺寸无效",
  "project path must use .pixio": "项目路径必须使用 .pixio 扩展名",
  "thumbnail is not a PNG image": "缩略图不是有效的 PNG 图片",
  "invalid canvas dimensions": "画布尺寸无效",
  "invalid project document": "项目文档无效",
  "invalid layer": "图层数据无效",
  "invalid frame": "帧数据无效",
  "invalid active layer or frame": "当前图层或帧无效",
  "invalid cel": "动画格数据无效",
  "project must contain one cel per layer and frame": "每个图层和帧都必须包含一个动画格",
  "Project cels are missing": "项目缺少动画格",
  "Project cel pixels are invalid": "动画格像素数据无效",
  "Project cel dimensions are invalid": "动画格尺寸无效",
  "Project contains duplicate cels": "项目包含重复的动画格",
  "Project JSON is invalid": "项目 JSON 无效",
  "Project document is invalid": "项目文档无效",
  "Invalid project response": "项目响应无效",
  "Invalid PNG response": "PNG 响应无效",
  "Recovery documents are missing": "恢复文件缺少文档",
  "Recovery document entry is invalid": "恢复文件中的文档条目无效",
  "Recovery JSON is invalid": "恢复文件 JSON 无效",
  "invalid JSON": "JSON 数据无效",
  "GIF frames and durations must be non-empty and equal": "GIF 帧和帧时长必须存在且数量一致",
  "GIF duration must be positive": "GIF 帧时长必须为正数",
  "sprite sheet needs at least one frame": "精灵图至少需要一帧",
  "sprite sheet is too wide": "精灵图宽度超出限制",
  "image dimensions must be positive": "图片尺寸必须为正数",
  "image dimensions must be positive and within limits": "图片尺寸必须为正数且不能超出限制",
  "Copied Selection": "已复制选区",
  "Copied Merged Selection": "已复制合并结果",
  "Fill Selection": "填充选区",
  "Stroke Selection": "描边选区",
  "Shift Pixels": "环绕平移像素",
  "Copy Selection to New Layer": "复制选区到新图层",
  "Cut Selection to New Layer": "剪切选区到新图层",
  "Paste as New Layer": "粘贴为新图层",
  "Paste as Reference Layer": "粘贴为参考图层",
  "Created project from clipboard": "已从剪贴板创建项目",
  "Selected All": "已全选",
  "Selected All Cels": "已选择当前图层全部动画格",
  "Selected Linked Cels": "已选择链接动画格",
  "Selection cleared": "已取消选区",
  "Scale Selection": "缩放选区",
  "Rotate Selection Clockwise": "顺时针旋转选区",
  "Rotate Selection Counterclockwise": "逆时针旋转选区",
  "Flip Selection Horizontally": "水平翻转选区",
  "Flip Selection Vertically": "垂直翻转选区",
  "Change Layer Opacity": "修改图层不透明度",
  "Change Cel Properties": "修改动画格属性",
  "MCP document edits": "MCP 文档编辑",
  "MCP set pixels": "MCP 像素编辑",
  "Select an image layer": "请选择图像图层",
  "Recent project is unavailable": "最近项目不可用",
  "Add Layer": "新建图层",
  "Add Layer Group": "新建图层组",
  "Delete Layer": "删除图层",
  "Duplicate Layer": "复制图层",
  "Rename Layer": "重命名图层",
  "Hide Layer": "隐藏图层",
  "Show Layer": "显示图层",
  "Lock Layer": "锁定图层",
  "Unlock Layer": "解锁图层",
  "Move Layer Up": "上移图层",
  "Move Layer Down": "下移图层",
  "Merge Layer Down": "向下合并图层",
  "Change Blend Mode": "修改混合模式",
  "Add Palette Color": "添加调色板颜色",
  "Edit Palette Color": "编辑调色板颜色",
  "Remove Palette Color": "移除调色板颜色",
  "Add Frame": "新建帧",
  "Duplicate Frame": "复制帧",
  "Delete Frame": "删除帧",
  "Move Frame": "移动帧",
  "Change Frame Rate": "修改帧率",
  "Link Cels": "链接所选动画格",
  "Unlink Cels": "取消链接所选动画格",
  "Add Frame Tag": "添加帧标签",
  "Edit Frame Tag": "编辑帧标签",
  "Delete Frame Tag": "删除帧标签",
  "Crop Canvas": "裁剪画布",
  "Resize Canvas": "调整画布尺寸",
  "Delete Selection": "删除选区",
  "Cut Selection": "剪切选区",
  "Paste Selection": "粘贴选区",
  "Selected Cels": "已选择动画格",
  "Copied Cels": "已复制动画格",
  "Cut Cels": "剪切动画格",
  "Clear Cels": "清除动画格",
  "Paste Cels": "粘贴动画格",
  "Selected cels are locked": "所选动画格已锁定",
  "Cels cannot be pasted here": "无法在此处粘贴动画格",
  "Unsupported clipboard content": "剪贴板内容不受支持",
  "selected project is already open": "所选项目已在其他标签中打开",
  "Rename Project": "重命名项目",
  "Add Guide": "添加辅助线",
  "Move Guide": "移动辅助线",
  "Delete Guide": "删除辅助线",
  "Change Grid": "修改网格",
  "Move Grid": "移动网格",
  "Change Grid Snapping": "修改网格吸附",
  "Change Symmetry": "修改对称设置",
  "Move Symmetry Axis": "移动对称轴",
  "Change Tiled Preview": "修改平铺预览",
  "Change Onion Skin": "修改洋葱皮",
  "Change Layer Role": "修改图层角色",
  "Layer Properties": "图层属性",
  "Duplicate Layers": "复制图层",
  "Move Layers": "移动图层",
  "Merge Selected Layers": "合并所选图层",
  "Flatten Visible Layers": "合并可见图层",
  "Create Cels": "创建动画格",
  "Delete Cels": "删除动画格",
  "Reverse Frames": "反转所选帧",
  "Add Tilemap Layer": "新建图块图层",
  "Convert Layer to Tilemap": "将图层转换为图块地图",
  "Add Tile": "添加图块",
  "Delete Tile": "删除图块",
  "Draw Tiles": "绘制图块",
  "Draw Tile Pixels": "绘制图块像素",
  "Change Color Mode": "修改颜色模式",
  "Assign Color Profile": "分配颜色配置文件",
  "Convert Color Profile": "转换颜色配置文件",
  "Assign Embedded Color Profile": "分配嵌入式颜色配置文件",
  "Import Palette": "导入调色板",
  "Extract Palette": "提取调色板",
  "Sort Palette": "整理调色板",
  "Text": "文字",
  "Outline": "轮廓",
  "Shading": "明暗处理",
  "Brightness / Contrast": "亮度 / 对比度",
  "Hue / Saturation / Lightness": "色相 / 饱和度 / 明度",
  "Invert Colors": "反相颜色",
  "Convolution": "卷积滤镜",
  "Median Filter": "中值滤波",
  "Despeckle": "去斑",
  "Color Curves": "颜色曲线",
  "HSV / HSL Adjustment": "HSV / HSL 调整",
  "Channel Mask": "通道掩码",
  "Transform Cels": "变换动画格",
  "Move Cels": "移动动画格",
  "Rasterize Cels": "将动画格栅格化到画布",
  "Move Selection": "移动选区",
  "Rotate Selection": "旋转选区",
  "Change Frame Duration": "修改帧时长",
  "Resize Sprite": "调整精灵内容尺寸",
  "Trim Canvas": "裁去画布透明边缘",
  "Rotate Sprite Clockwise": "顺时针旋转精灵",
  "Rotate Sprite Counterclockwise": "逆时针旋转精灵",
  "Rotate Sprite 180": "旋转精灵 180°",
  "Flip Sprite Horizontally": "水平翻转精灵",
  "Flip Sprite Vertically": "垂直翻转精灵",
  "Add Slice": "添加切片",
  "Move Slices": "移动切片",
  "Scale Slices": "缩放切片",
  "Delete Slices": "删除切片",
  "Slice Properties": "切片属性",
  "Edit Slice": "编辑切片",
  "Edit Slice Pivot": "编辑切片中心点",
  "Rename Slice": "重命名切片",
  "Toggle Nine-patch": "切换九宫格",
  "Delete Slice": "删除切片",
  "History state restored": "已恢复历史状态",
  "Exporting PNG sequence...": "正在导出 PNG 序列...",
  "Sequence export failed": "序列导出失败",
  "No editable cels selected": "没有选择可编辑的动画格",
  "No editable image cels": "没有可编辑的图像动画格",
  "Text rendering failed": "文字渲染失败",
  "Exported packed atlas": "已导出紧凑图集",
  "Pause playback to edit": "暂停播放后才能编辑",
};
