import {
Blend,
BoxSelect,
Circle,
Crop,
Droplets,
Eraser,
Hand,
Move,
PaintBucket,
Pencil,
Pentagon,
Pipette,
Replace,
Scaling,
Shuffle,
Slash,
Slice as SliceIcon,
Spline,
SprayCan,
Square,
SquaresUnite,
Type,
Waypoints,
ZoomIn,
type LucideIcon
} from "lucide-react";
import {type ToolID} from "../editor/tools";

export const tools: Array<{id: ToolID; icon: LucideIcon}> = [
  {id: "pencil", icon: Pencil},
  {id: "eraser", icon: Eraser},
  {id: "eyedropper", icon: Pipette},
  {id: "zoom", icon: ZoomIn},
  {id: "hand", icon: Hand},
  {id: "move", icon: Move},
  {id: "line", icon: Slash},
  {id: "rectangle", icon: Square},
  {id: "ellipse", icon: Circle},
  {id: "curve", icon: Spline},
  {id: "polyline", icon: Waypoints},
  {id: "polygon", icon: Pentagon},
  {id: "fill", icon: PaintBucket},
  {id: "gradient", icon: Blend},
  {id: "spray", icon: SprayCan},
  {id: "blur", icon: Droplets},
  {id: "jumble", icon: Shuffle},
  {id: "contour", icon: SquaresUnite},
  {id: "replace-color", icon: Replace},
  {id: "selection", icon: BoxSelect},
  {id: "transform", icon: Scaling},
  {id: "crop", icon: Crop},
  {id: "slice", icon: SliceIcon},
  {id: "text", icon: Type},
];

export const toolDefinitionByID = new Map(tools.map((tool) => [tool.id, tool]));
