// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClaimMCPCommand(arg1) {
  return window['go']['main']['App']['ClaimMCPCommand'](arg1);
}

export function ClearRecovery() {
  return window['go']['main']['App']['ClearRecovery']();
}

export function ClipboardReadImage() {
  return window['go']['main']['App']['ClipboardReadImage']();
}

export function ClipboardWriteImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['ClipboardWriteImage'](arg1, arg2, arg3);
}

export function CompleteMCPCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['CompleteMCPCommand'](arg1, arg2, arg3);
}

export function ImportPNG(arg1) {
  return window['go']['main']['App']['ImportPNG'](arg1);
}

export function ImportPNGSequence(arg1) {
  return window['go']['main']['App']['ImportPNGSequence'](arg1);
}

export function LoadRecovery() {
  return window['go']['main']['App']['LoadRecovery']();
}

export function OpenPixio(arg1) {
  return window['go']['main']['App']['OpenPixio'](arg1);
}

export function OpenPixioPath(arg1) {
  return window['go']['main']['App']['OpenPixioPath'](arg1);
}

export function OpenStartupProject() {
  return window['go']['main']['App']['OpenStartupProject']();
}

export function OpenTilemapData(arg1) {
  return window['go']['main']['App']['OpenTilemapData'](arg1);
}

export function SaveGIF(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SaveGIF'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SaveGIFWithOptions(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['SaveGIFWithOptions'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function SavePNG(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SavePNG'](arg1, arg2, arg3, arg4);
}

export function SavePNGSequence(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SavePNGSequence'](arg1, arg2, arg3, arg4, arg5);
}

export function SavePNGWithOptions(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SavePNGWithOptions'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SavePackedAtlas(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SavePackedAtlas'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SavePixio(arg1, arg2, arg3) {
  return window['go']['main']['App']['SavePixio'](arg1, arg2, arg3);
}

export function SavePixioPath(arg1, arg2) {
  return window['go']['main']['App']['SavePixioPath'](arg1, arg2);
}

export function SaveRecovery(arg1) {
  return window['go']['main']['App']['SaveRecovery'](arg1);
}

export function SaveSpriteSheet(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['SaveSpriteSheet'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function SaveSpriteSheetWithOptions(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13) {
  return window['go']['main']['App']['SaveSpriteSheetWithOptions'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
}

export function SaveTilemapData(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveTilemapData'](arg1, arg2, arg3, arg4);
}

export function SetMCPReady(arg1) {
  return window['go']['main']['App']['SetMCPReady'](arg1);
}

export function SetWindowCloseState(arg1, arg2) {
  return window['go']['main']['App']['SetWindowCloseState'](arg1, arg2);
}
