// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClaimMCPCommand(arg1:string):Promise<boolean>;

export function ClearRecovery():Promise<void>;

export function ClipboardReadImage():Promise<string>;

export function ClipboardWriteImage(arg1:number,arg2:number,arg3:string):Promise<void>;

export function CompleteMCPCommand(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ImportPNG(arg1:string):Promise<string>;

export function ImportPNGSequence(arg1:string):Promise<string>;

export function LoadRecovery():Promise<string>;

export function OpenPixio(arg1:string):Promise<string>;

export function OpenPixioPath(arg1:string):Promise<string>;

export function OpenStartupProject():Promise<string>;

export function OpenTilemapData(arg1:string):Promise<string>;

export function SaveGIF(arg1:number,arg2:number,arg3:Array<string>,arg4:Array<number>,arg5:number,arg6:number,arg7:string):Promise<string>;

export function SaveGIFWithOptions(arg1:number,arg2:number,arg3:Array<string>,arg4:Array<number>,arg5:number,arg6:number,arg7:boolean,arg8:number,arg9:number,arg10:string):Promise<string>;

export function SavePNG(arg1:number,arg2:number,arg3:string,arg4:string):Promise<string>;

export function SavePNGSequence(arg1:number,arg2:number,arg3:Array<string>,arg4:string,arg5:string):Promise<string>;

export function SavePNGWithOptions(arg1:number,arg2:number,arg3:string,arg4:boolean,arg5:number,arg6:number,arg7:string):Promise<string>;

export function SavePackedAtlas(arg1:number,arg2:number,arg3:string,arg4:string,arg5:boolean,arg6:string):Promise<string>;

export function SavePixio(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;

export function SavePixioPath(arg1:string,arg2:string):Promise<string>;

export function SaveRecovery(arg1:string):Promise<void>;

export function SaveSpriteSheet(arg1:number,arg2:number,arg3:Array<string>,arg4:string,arg5:number,arg6:number,arg7:number,arg8:number,arg9:boolean,arg10:string):Promise<string>;

export function SaveSpriteSheetWithOptions(arg1:number,arg2:number,arg3:Array<string>,arg4:string,arg5:number,arg6:number,arg7:number,arg8:number,arg9:boolean,arg10:boolean,arg11:number,arg12:number,arg13:string):Promise<string>;

export function SaveTilemapData(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SetMCPReady(arg1:boolean):Promise<void>;

export function SetWindowCloseState(arg1:boolean,arg2:string):Promise<void>;
